export const SEARCH_MOVIES = "SEARCH_MOVIES";

export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES = "GET_MOVIES";

export const ADD_MOVIES_REQUEST = "ADD_MOVIES_REQUEST";
export const ADD_MOVIES = "ADD_MOVIES";

export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE = "GET_MOVIE";

export const GET_MOVIES_TRAKT_REQUEST = "GET_MOVIES_TRAKT_REQUEST";
export const GET_MOVIES_TRAKT = "GET_MOVIES_TRAKT";

export const ADD_MOVIES_TRAKT = "ADD_MOVIES_TRAKT";
export const ADD_MOVIES_TRAKT_REQUEST = "ADD_MOVIES_TRAKT_REQUEST";

export const RESET_MOVIES = "RESET_MOVIES";
