export const GET_SERIALS_REQUEST = "GET_SERIALS_REQUEST";
export const GET_SERIALS = "GET_SERIALS";
export const GET_SERIALS_FAIL = "GET_SERIALS_FAIL";

export const SEARCH_SERIALS = "SEARCH_SERIALS";

export const ADD_SERIALS_REQUEST = "ADD_SERIALS_REQUEST";
export const ADD_SERIALS = "ADD_SERIALS";

export const GET_SERIAL_REQUEST = "GET_SERIAL_REQUEST";
export const GET_SERIAL = "GET_SERIAL";

export const GET_EPISODE_REQUEST = "GET_EPISODE_REQUEST";
export const GET_EPISODE = "GET_EPISODE";
