export const GET_SUBTITLES_REQUEST = "GET_SUBTITLES_REQUEST";
export const GET_SUBTITLES = "GET_SUBTITLES";
export const SET_SUBTITLE = "SET_SUBTITLE";
export const RESET_STATES_SUBTITLES = "RESET_STATES_SUBTITLES";
