export const GET_TORRENTS_REQUEST = "GET_TORRENTS_REQUEST";
export const GET_TORRENTS = "GET_TORRENTS";

export const DOWNLOAD_TORRENT_REQUEST = "DOWNLOAD_TORRENT_REQUEST";
export const DOWNLOAD_TORRENT = "DOWNLOAD_TORRENT";

export const STOP_TORRENT_REQUEST = "STOP_TORRENT_REQUEST";
export const STOP_TORRENT = "STOP_TORRENT";

export const RESET_STATES_TORRENTS = "RESET_STATES_TORRENTS";
